### ISSUE TITLE
Support for color pictures

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/colorize#4]
Actually, you can `ml score AColorPicture`, internally it will be converted to a grayscale black-white picture.  So it it better to demonstrate the original color picture, the grayscale one and the colorized results in a row together, instead of only showing the balck-white and results without the orignal color picture.

**Comment by boulaziz** [comment]
I am getting the following error:
./.local/bin/ml color   colorize --interactive Six_chefs.png
Traceback (most recent call last):
  File "./.local/bin/ml", line 11, in <module>
    sys.exit(main())
  File "/home/khaled/.local/lib/python3.6/site-packages/mlhub/__init__.py", line 197, in main
    args.func(args)
  File "/home/khaled/.local/lib/python3.6/site-packages/mlhub/commands.py", line 1061, in dispatch
    errors = errors.decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by gjwgit** [comment]
This issue is about colouring coloured photos and not for new issues with the package. Moved to #6.
